---
development:
  cloud_name: rosiene
  api_key: '754231632654115'
  api_secret: BvDjV9lh7DpSOl7F7uWlVKFygXM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: rosiene
  api_key: '754231632654115'
  api_secret: BvDjV9lh7DpSOl7F7uWlVKFygXM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: rosiene
  api_key: '754231632654115'
  api_secret: BvDjV9lh7DpSOl7F7uWlVKFygXM
  enhance_image_tag: true
  static_image_support: false
